name: Build workflow
run-name: Build workflow
on:
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4

      - name: Run in ARM64 container
        run: |
            cd /home/git/binary-com/perl/
            git commit --allow-empty -am"test dummy"
            git remote add dev git@github.com:qiangliu-deriv/perl.git
            git push dev HEAD:testlq
            git push origin HEAD:testlq


